### ISSUE TITLE
Create room generator

### ISSUE THREAD

**Issue by peschkaj** [legitbiz/SealsOfFate#7]
- [ ] Room procedural generation tools
- [ ] Implementation of `LevelManager`

Room creation:
- A room has more than one entrance
- A room has between 1 and 4 (inclusive) exits
- A room has 1 or more features
- A room has a scaled % of drops
- A room has a scaled % of enemies

**Comment by peschkaj** [comment]
Where are we on room generation right now?

**Comment by connorkuehl** [comment]
In terms of application: not far. In terms of design, we're circling around a pretty viable approach (at least, we think so). 

After our initial refinement of the algorithm to generate levels, Doug and I split off a little bit since every variant of this algorithm depends on a Graph data structure. The initial implementation of the Graph is done as of PR #53, so we should be ready to begin working on actual level generation now.
