### ISSUE TITLE
🐞Intermittent Pathfinding Crash

### ISSUE THREAD

**Issue by Zonr0** [legitbiz/SealsOfFate#81]
Pathfinding sporadically crashes for unknown reasons citing a collection in an invalid state.

Reproduction:
1. Load up a game
1. Run around until you crash, or restart if none happens
1. Note the circumstances in which the crash occurred

**Comment by connorkuehl** [comment]
I _think_ I might have somewhat a solution for the invalid state. However, even with this, there was one occasion where the Enemy reported it could not find a path to the Player and I got a hang there too, but I didn't get the invalid state error message. Could be a matter of it crashing so hard it couldn't log it, but here's my findings so far:

Line 80 in `SearchAStar.cs`, I changed the LINQ method from `Single` to `First`, because `Single` will [throw an exception](https://msdn.microsoft.com/en-us/library/bb535118(v=vs.110).aspx)  if more than one item matches (in case for whatever reason there's a duplicate item in the collection).

Aside from that one hang with the Enemy not being able to route to the Player, I haven't experienced any other hangs after switching the LINQ method from `Single` to `First`.

Again, not sure if it's a fix. Just jotting my notes in hopes that it helps narrow things down.

**Comment by Zonr0** [comment]
Good catch on that. I did some digging and a few well placed conditional breakpoints later, it looks like openlist is growing to infinity bouncing back and forth between two nodes. That theoretically shouldn't happen in A* as I understand it, so I'll need to review the algorithm for mistakes.
